export const FETCH_COCKTAIL_START = "FETCH_COCKTAIL_START";
export const FETCH_COCKTAIL_SUCCESS = "FETCH_COCKTAIL_SUCCESS";
export const FETCH_COCKTAIL_FAIL = "FETCH_COCKTAIL_FAIL";

export const SEARCH_COCKTAIL_START = "SEARCH_COCKTAIL_START";
export const SEARCH_COCKTAIL_SUCCESS = "SEARCH_COCKTAIL_SUCCESS";
export const SEARCH_COCKTAIL_FAIL = "SEARCH_COCKTAIL_FAIL";

export const GET_SINGLE_COCKTAIL_START = "GET_SNGLE_COCKTAIL_START";
export const GET_SINGLE_COCKTAIL_SUCCESS = "GET_SINGLE_COCKTAIL_SUCCESS";
export const GET_SINGLE_COCKTAIL_FAIL = "GET_SINGLE_COCKTAIL_FAIL";

// Add drink to favorites
export const ADD_DRINK_TO_FAVOURITES_START = "ADD_DRINK_TO_FAVOURITES_START";
export const ADD_DRINK_TO_FAVOURITES_SUCCESS = "ADD_DRINK_TO_FAVOURITES_SUCCESS";
export const ADD_DRINK_TO_FAVOURITES_FAIL = "ADD_DRINK_TO_FAVOURITES_FAIL";

// Remove drink from favorites
export const REMOVE_FROM_FAVOURITES_START = "REMOVE_FROM_FAVOURITES_START";
export const REMOVE_FROM_FAVOURITES_SUCCESS = "REMOVE_FROM_FAVOURITES_SUCCESS";
export const REMOVE_FROM_FAVOURITES_FAIL = "REMOVE_FROM_FAVOURITES_FAIL";
